point to unversioned due to an error when I use brew install
==> Downloading https://yext-cli-pub.s3.amazonaws.com/cli/mac/yext-55c4a3c932b2647
######################################################################## 100.0%
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - yext